site_name: PyMojang
repo_url: https://github.com/Lucino772/pymojang
site_author: Lucino772

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings

extra_css:
  - css/extra.css

nav:
  - Quisk Start:
    - 'Installation': 'index.md'
    - 'Basic Usage': 'basic.md'
  
  - Advanced:
    - 'Profile and Authentication': 'advanced.md'

  - PyMojang:
    - 'mojang.api.auth.yggdrasil': 'PyMojang/yggdrasil.md'
    - 'mojang.api.auth.security': 'PyMojang/security.md'
    - 'mojang.api.base': 'PyMojang/base.md'
    - 'mojang.api.session': 'PyMojang/session.md'
    - 'mojang.profile.UserProfile': 'PyMojang/UserProfile.md'
    - 'mojang.session.UserSession': 'PyMojang/UserSession.md' 
    - 'Exceptions': 'PyMojang/exceptions.md'
