site_name: PyMojang
repo_url: https://github.com/Lucino772/pymojang
repo_name: Lucino772/PyMojang
site_author: Lucino772

theme: 
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      watch:
        - mojang

extra_css:
  - css/extra.css

extra:
  version:
    provider: mike
    default: stable

nav:
  - What is PyMojang: 'index.md'
  - Check Status: 'check_status.md'
  - Account:
    - Retrieve user information: 'account/retrieve_user_info.md'
    - Authenticated User:
      - Connect: 'account/auth_connect.md'
      - Auth API: 'account/auth_api.md'
      - Security API: 'account/auth_security.md'
      - Session API: 'account/auth_session.md'
  - Minecraft:
    - RCON: 'minecraft/rcon.md'
    - Query: 'minecraft/query.md'
    - Server List Ping: 'minecraft/slp.md'
